"use strict";

import { Repository } from "./Repository";
import { Entity } from "./Entity";

export interface Persistor {
    /**
     * @function setAutoCommit
     * 
     * @param autoCommit 
     */
    setAutoCommit(autoCommit: boolean): void;
    getAutoGeneratedKey(): number;
    insert(repository: Repository, entities: Entity | Entity[]): number;
    delete(repository: Repository, entityToRemove: Entity): number;
    update(repository: Repository, entityToUpdate: Entity): number;
    findAll(repository: Repository): Entity[];
    deleteWhere(repository: Repository, conditions): number;
    findWhere(repository: Repository, conditions): Entity[];
    findOne(repository: Repository, PKValue: any): Entity;
}
